#!/usr/bin/env bash
#   Bash script that uses ssh to connect to your server
#   using the private key ~/.ssh/school with the user ubuntu.
#  Only use ssh single-character flags
#   You cannot use -l
#   Dont handle the case of a private key protected by a passphrase

ssh -i ~/.ssh/school ubuntu@34.224.94.25
