#!/usr/bin/env bash
# Your SSH client configuration must be configured
# to use the private key ~/.ssh/school
# Your SSH client configuration must be configured 
# to refuse to authenticate using a password

Host school
    HostName 35.153.194.29
    User ubuntu
    PasswordAuthentication no
	IdentityFile ~/.ssh/school