#!/usr/bin/env bash
# Your SSH client configuration must be configured
# to use the private key ~/.ssh/school
# Your SSH client configuration must be configured 
# to refuse to authenticate using a password

Host school
    HostName 100.25.119.219
    User ubuntu
